# **Case Passos Mágicos**

**Mudando a vida de crianças e jovens por meio da educação**

A Associação Passos Mágicos tem uma trajetória de 35 anos de atuação, trabalhando na transformação da vida de crianças e jovens de baixa renda, levando-os a melhores oportunidades de vida. A transformação, idealizada por Michelle Flues e Dimetri Ivanoff, começou em 1992, atuando dentro de orfanatos no município de Embu-Guaçu.

Em 2016, depois de anos de atuação, decidiram ampliar o programa para que mais jovens tivessem acesso a essa fórmula mágica para transformação que inclui: educação de qualidade, auxílio psicológico/psicopedagógico, ampliação de sua visão de mundo e protagonismo. Passaram, então, a atuar como um projeto social e educacional, criando assim a Associação Passos Mágicos.

A associação busca instrumentalizar o uso da educação como ferramenta para a mudança das condições de vida das crianças e jovens em vulnerabilidade social. Com base no dataset de pesquisa extensiva do desenvolvimento educacional no período de 2022, 2023 e 2024, você tem um desafio de data analytics para trazer um impacto real na vida dessas crianças.

Utilizando estratégias de analytics aprendidas aqui no curso da PosTech, você tem o desafio de responder a algumas dores de negócio listadas neste documento, em um formato de apresentação gerencial e analítico, contando uma história com os dados, trazendo resposta às perguntas e sugerindo oportunidade de melhoria no processo atual. Além da prática de análise de dados e storytelling, esse desafio também traz o desafio do desenvolvimento de um modelo preditivo.
[texto do link](https://)

# **Perguntas para análise**

1. Adequação do nível (IAN)
Qual é o perfil geral de defasagem dos alunos (IAN) e como ele evolui ao longo do ano?
(Ex.: quantos alunos estão moderadamente ou severamente defasados?)

2. Desempenho acadêmico (IDA)
O desempenho acadêmico médio (IDA) está melhorando, estagnado ou caindo ao longo das fases e anos?

3. Engajamento nas atividades (IEG)
O grau de engajamento dos alunos (IEG) tem relação direta com seus indicadores de desempenho (IDA) e do ponto de virada (IPV)?

4. Autoavaliação (IAA)
As percepções dos alunos sobre si mesmos (IAA) são coerentes com seu desempenho real (IDA) e engajamento (IEG)?

5. Aspectos psicossociais (IPS)
Há padrões psicossociais (IPS) que antecedem quedas de desempenho acadêmico ou de engajamento?

6. Aspectos psicopedagógicos (IPP)
As avaliações psicopedagógicas (IPP) confirmam ou contradizem a defasagem identificada pelo IAN?

7. Ponto de virada (IPV)
Quais comportamentos - acadêmicos, emocionais ou de engajamento - mais influenciam o IPV ao longo do tempo?

8. Multidimensionalidade dos indicadores
Quais combinações de indicadores (IDA + IEG + IPS + IPP) elevam mais a nota global do aluno (INDE)?

9. Previsão de risco com Machine Learning
Quais padrões nos indicadores permitem identificar alunos em risco antes de queda no desempenho ou aumento da defasagem? Construa um modelo preditivo que mostre uma probabilidade do aluno ou aluna entrar em risco de defasagem.

10. Efetividade do programa
Os indicadores mostram melhora consistente ao longo do ciclo nas diferentes fases (Quartzo, Ágata, Ametista e Topázio), confirmando o impacto real do programa?

11. Insights e criatividade
Você pode adicionar mais insights e pontos de vista não abordados nas perguntas, utilize a criatividade e a análise dos dados para trazer sugestões para a Passos Mágicos.

### **dicionario**

INSTITUICAO_ENSINO_ALUNO_2020 -Mostra instituiça o de Ensino do Aluno em 2020
**NOME** - Nome do Aluno (Dados esta o Anonimizados)

**IDADE_ALUNO_2020** -Idade do Aluno em 2020

**ANOS_NA_PM_2020** -Tempo (Em Anos) que o Alunos esta na Passos Ma gicos em 2020

**FASE_TURMA_2020** -Fase e Turma do Aluno na Passos Ma gicos em 2020; Fase esta relacionado ao Ní vel de Aprendizado, enquanto Turma e dado pela quantidade de turmas que existam daquela fase/ní vel

**PONTO_VIRADA_2020** -Campo do Tipo Booleano que sinaliza se o Aluno atingiu o “Ponto de Virada” em 2020

**INDE_2020** -Indice do Desenvolvimento Educacional – Me trica de Processo Avaliativo Geral do Aluno; Dado pela Ponderaça o dos indicadores: IAN, IDA, IEG, IAA, IPS, IPP e IPV em 2020

**INDE_CONCEITO_2020**

**PEDRA_2020** - Classificaça o do Aluno baseado no nu mero do INDE, o conceito de classificaça o e dado por:

    Quartzo – 2,405 a 5,506
    Agata – 5,506 a 6,868
    Ametista – 6,868 a 8,230
    Topazio – 8,230 a 9,294.

Cada Pedra possui uma descriçao

**DESTAQUE_IEG_2020** -Observaço es dos Avaliadores Sobre o Aluno referente ao "Indicador de Engajamento” em 2020

**DESTAQUE_IDA_2020** -Observaço es dos Avaliadores Sobre o Aluno referente ao “Indicador de Aprendizagem” em 2020

**DESTAQUE_IPV_2020** - Observaço es dos Avaliadores Sobre o Aluno referente ao “Indicador de Ponto de Virada” em 2020

**IAA_2020** - Indicador de Auto Avaliça o – Me dia das Notas de Auto Avaliaça o do Aluno em 2020

**IEG_2020** -Indicador de Engajamento – Me dia das Notas de Engajamento do Aluno em 2020

**IPS_2020** -Indicador Psicossocial – Me dia das Notas Psicossociais do Aluno em 2020

**IDA_2020** -Indicador de Aprendizagem - Me dia das Notas do Indicador de Aprendizagem

**IPP_2020** -Indicador Psicopedago gico – Me dia das Notas Psico Pedago gicas do Aluno em 2020

**IPV_2020** -Indicador de Ponto de Virada – Me dia das Notas de Ponto de Virada do Aluno em 2020

**IAN_2020** -Indicador de Adequaça o ao Nível – Media das Notas de Adequaça o do Aluno ao ní vel atual em 2020

**FASE_2021** -Fase e o Ní vel de Aprendizado do Aluno em 2021

**TURMA_2021** -Turma e o nu mero da Turma de cada fase (1A,1B,1C)

**INSTITUICAO_ENSINO_ALUNO_2021** -Mostra instituiça o de Ensino do Aluno em 2021

**SINALIZADOR_INGRESSANTE_2021** -Mostra se o Aluno Ingressou ou e Veterano no ano de 2021

**PEDRA_2021** -Classificaça o do Aluno baseado no nu mero do INDE, o conceito de classificaça o e dado por:

    Quartzo – 2,405 a 5,506
    Agata – 5,506 a 6,868
    Ametista – 6,868 a 8,230
    Topazio – 8,230 a 9,294.

Cada Pedra possui uma descriçao

**INDE_2021** -I ndice do Desenvolvimento Educacional – Me trica de Processo Avaliativo Geral do Aluno; Dado pela Ponderaça o dos indicadores: IAN, IDA, IEG, IAA, IPS, IPP e IPV em 2021

**IAA_2021** -Indicador de Auto Avaliça o – Me dia das Notas de Auto Avaliaça o do Aluno em 2021

**IEG_2021** -Indicador de Engajamento – Me dia das Notas de Engajamento do Aluno em 2021

**IPS_2021** -Indicador Psicossocial – Me dia das Notas Psicossociais do Aluno em 2021

**REC_PSICO_2021** -Mostra qual a recomendaça o da equipe de psicologia sobre o Aluno em 2021

**IDA_2021** - Indicador de Aprendizagem - Me dia das Notas do Indicador de Aprendizagem em 2021

**IPP_2021** - Indicador Psicopedago gico – Me dia das Notas Psicopedago gicas do Aluno em 2021

**REC_EQUIPE_1_2021** - Recomendaça o da Equipe de Avaliça o 1 em 2021

**REC_EQUIPE_2_2021** - Recomendaça o da Equipe de Avaliça o 2 em 2021

**REC_EQUIPE_3_2021** -Recomendaça o da Equipe de Avaliça o 3 em 2021

**REC_EQUIPE_4_2021** - Recomendaça o da Equipe de Avaliça o 3 em 2021

**PONTO_VIRADA_2021** -Campo do Tipo Booleano que sinaliza se o Aluno atingiu o “Ponto de Virada” em 2021.

**IPV_2021** -Indicador de Ponto de Virada – Me dia das Notas de Ponto de Virada do Aluno em 2021

**IAN_2021** - Indicador de Adequaça o ao Ní vel – Me dia das Notas de Adequaça o do Aluno ao ní vel atual em 2021.

**NIVEL_IDEAL_2021** -
Mostra qual o ní vel (Fase) ideal do Aluno na Passos Ma gicos em 2021

**DEFASAGEM_2021** - Mostra o ní vel de defasagem do ano em 2021

**FASE_2022** -Fase e o Ní vel de Aprendizado do Aluno

**TURMA_2022** -Turma e o nu mero da Turma de cada fase (1A,1B,1C)

**ANO_INGRESSO_2022**- Ano que o Aluno Ingressou na Passos Ma gicos (atualizado 2022)

**BOLSISTA_2022** -Campo do tipo booleano que mostra se o Aluno e Bolsista em alguma instituiça o pela Passos Ma gicos em 2022

**INDE_2022** -I ndice do Desenvolvimento Educacional – Me trica de Processo Avaliativo Geral do Aluno; Dado pela Ponderaça o dos indicadores: IAN, IDA, IEG, IAA, IPS, IPP e IPV em 2022

**CG_2022** -Classificaça o (Ranking) Geral do Aluno na Passos Ma gicos em 2022

**CF_2022** - Classificaça o (Ranking) do Aluno na Fase em 2022

**CT_2022** -Classificaça o (Ranking) do Aluno na Turma em 2022

**PEDRA_2022** -Classificaça o do Aluno baseado no nu mero do INDE, o conceito de classificaça o e dado por:

    Quartzo – 2,405 a 5,506
    Agata – 5,506 a 6,868
    Ametista – 6,868 a 8,230
    Topazio – 8,230 a 9,294.

Cada Pedra possui uma descriça o.

**DESTAQUE_IEG_2022** -Observaço es dos Mestres Sobre o Aluno referente ao "Indicador de Engajamento” em 2022

**DESTAQUE_IDA_2022** -Observaço es dos Mestres Sobre o Aluno referente ao “Indicador de Aprendizagem” em 2022

**DESTAQUE_IPV_2022** -Observaço es dos Mestres Sobre o Aluno referente ao “Indicador de Ponto de Virada” em 2022

**IAA_2022** -Indicador de Auto Avaliça o – Me dia das Notas de Auto Avaliaça o do Aluno em 2022

**IEG_2022** -Indicador de Engajamento – Me dia das Notas de Engajamento do Aluno em 2022

**IPS_2022** -Indicador Psicossocial – Me dia das Notas Psicossociais do Aluno em 2022

**REC_PSICO_2022** -Mostra qual a recomendaça o da equipe de psicologia sobre o Aluno em 2022

**IDA_2022** - Indicador de Aprendizagem - Me dia das Notas do Indicador de Aprendizagem em 2022

**NOTA_PORT_2022** -Me dia das Notas de Portugue s do Aluno em 2022

**NOTA_MAT_2022** - Me dia das Notas de Matema tica do Aluno em 2022

**NOTA_ING_2022** -Me dia das Notas de Ingle s do Aluno em 2022

**QTDE_AVAL_2022** - Quantidade de Avaliaço es do Aluno em 2022

**REC_AVA_1_2022** -Recomendaça o da Equipe de Avaliça o 1 em 2022

**REC_AVAL_2_2022** - Recomendaça o da Equipe de Avaliça o 2 em 2022

**REC_AVAL_3_2022** -Recomendaça o da Equipe de Avaliça o 3 em 2022

**REC_AVAL_4_2022** -Recomendaça o da Equipe de Avaliça o 3 em 2022

**INDICADO_BOLSA_2022** -Campo do Tipo Booleano que sinaliza se o Aluno foi indicado para alguma Bolsa no Ano de 2022

**PONTO_VIRADA_2022** -Campo do Tipo Booleano que sinaliza se o Aluno atingiu o “Ponto de Virada” em 2022.

**IPV_2022** -Indicador de Ponto de Virada – Me dia das Notas de Ponto de Virada do Aluno em 2022

**IAN_2022** -Indicador de Adequaça o ao Ní vel – Me dia das Notas de Adequaça o do Aluno ao ní vel atual em 2022.

**NIVEL_IDEAL_2022** - Mostra qual o ní vel(Fase) ideal do Aluno na Passos Ma gicos em 2022

In [1]:
import pandas as pd

In [2]:
url_github = "https://github.com/aluizio142-ops/Datathon---Case-Passos-Magicos/raw/refs/heads/main/BASE%20DE%20DADOS%20PEDE%202024.xlsx"
df = pd.read_excel(url_github, sheet_name=None)

carregado arquivo no github e colocado como um "unico arquivo", ele fica desestruturado, em caso de tratar ele inteiro.
dessa forma, o ideal é criar df para cada ano/aba que há no excel.

In [3]:
df

{'PEDE2022':          RA  Fase Turma       Nome  Ano nasc  Idade 22  Gênero  Ano ingresso  \
 0      RA-1     7     A    Aluno-1      2003        19  Menina          2016
 1      RA-2     7     A    Aluno-2      2005        17  Menina          2017
 2      RA-3     7     A    Aluno-3      2005        17  Menina          2016
 3      RA-4     7     A    Aluno-4      2005        17  Menino          2017
 4      RA-5     7     A    Aluno-5      2005        17  Menina          2016
 ..      ...   ...   ...        ...       ...       ...     ...           ...
 855  RA-856     0     Z  Aluno-856      2015         7  Menino          2022
 856  RA-857     0     Z  Aluno-857      2013         9  Menina          2022
 857  RA-858     0     Z  Aluno-858      2015         7  Menino          2022
 858  RA-859     0     Z  Aluno-859      2015         7  Menina          2022
 859  RA-860     0     Z  Aluno-860      2015         7  Menino          2022

     Instituição de ensino  Pedra 20  ... Inglês Indicado  Atingiu PV    IPV  \
 0          Escola Pública  Ametista  ...    6.0      Sim         Não  7.278
 1            Rede Decisão  Ametista  ...    9.7      Não         Não  6.778
 2            Rede Decisão  Ametista  ...    6.9      Não         Não  7.556
 3            Rede Decisão  Ametista  ...    8.7      Não         Não  5.278
 4            Rede Decisão  Ametista  ...    5.7      Não         Não  7.389
 ..                    ...       ...  ...    ...      ...         ...    ...
 855        Escola Pública       NaN  ...    NaN      Não         Não  8.000
 856        Escola Pública       NaN  ...    NaN      Não         Sim  9.083
 857        Escola Pública       NaN  ...    NaN      Não         Não  7.333
 858        Escola Pública       NaN  ...    NaN      Não         Não  8.250
 859        Escola Pública       NaN  ...    NaN      Não         Não  7.750

       IAN               Fase ideal  Defas  \
 0     5.0  Fase 8 (Universitários)     -1
 1    10.0           Fase 7 (3º EM)      0
 2    10.0           Fase 7 (3º EM)      0
 3    10.0           Fase 7 (3º EM)      0
 4    10.0           Fase 7 (3º EM)      0
 ..    ...                      ...    ...
 855  10.0      ALFA  (2º e 3º ano)      0
 856   5.0          Fase 1 (4º ano)     -1
 857  10.0      ALFA  (2º e 3º ano)      0
 858  10.0      ALFA  (2º e 3º ano)      0
 859  10.0      ALFA  (2º e 3º ano)      0

                                           Destaque IEG  \
 0    Melhorar: Melhorar a sua entrega de lições de ...
 1    Melhorar: Melhorar a sua entrega de lições de ...
 2      Destaque: A sua boa entrega das lições de casa.
 3    Melhorar: Melhorar a sua entrega de lições de ...
 4      Destaque: A sua boa entrega das lições de casa.
 ..                                                 ...
 855    Destaque: A sua boa entrega das lições de casa.
 856    Destaque: A sua boa entrega das lições de casa.
 857  Melhorar: Melhorar a sua entrega de lições de ...
 858    Destaque: A sua boa entrega das lições de casa.
 859    Destaque: A sua boa entrega das lições de casa.

                                           Destaque IDA  \
 0    Melhorar: Empenhar-se mais nas aulas e avaliaç...
 1    Melhorar: Empenhar-se mais nas aulas e avaliaç...
 2    Melhorar: Empenhar-se mais nas aulas e avaliaç...
 3    Melhorar: Empenhar-se mais nas aulas e avaliaç...
 4    Melhorar: Empenhar-se mais nas aulas e avaliaç...
 ..                                                 ...
 855    Destaque: As suas boas notas na Passos Mágicos.
 856    Destaque: As suas boas notas na Passos Mágicos.
 857    Destaque: As suas boas notas na Passos Mágicos.
 858    Destaque: As suas boas notas na Passos Mágicos.
 859    Destaque: As suas boas notas na Passos Mágicos.

                                           Destaque IPV
 0    Melhorar: Integrar-se mais aos Princípios Pass...
 1    Melhorar: Integrar-se mais aos Princípios Pass...
 2    Destaque: A sua boa integração aos Princípios ...
 3    Melhorar: Integrar-se mais aos Princípios Pass...
 4    Melhorar: Integrar-se mais aos Princípios Pass...
 ..                                                 ...
 855  Destaque: A sua boa integração aos Princípios ...
 856  Destaque: A sua boa integração aos Princípios ...
 857  Melhorar: Integrar-se mais aos Princípios Pass...
 858  Destaque: A sua boa integração aos Princípios ...
 859  Destaque: A sua boa integração aos Princípios ...

 [860 rows x 42 columns],
 'PEDE2023':            RA    Fase  INDE 2023 Pedra 2023           Turma Nome Anonimizado  \
 0      RA-861    ALFA    9.31095    Topázio  ALFA A - G0/G1        Aluno-861
 1      RA-862    ALFA    8.22120    Topázio  ALFA A - G0/G1        Aluno-862
 2      RA-863    ALFA    5.92975    Quartzo  ALFA A - G0/G1        Aluno-863
 3      RA-864    ALFA    7.03400   Ametista  ALFA A - G0/G1        Aluno-864
 4      RA-865    ALFA    8.15520    Topázio  ALFA A - G0/G1        Aluno-865
 ...       ...     ...        ...        ...             ...              ...
 1009     RA-2  FASE 8        NaN        NaN              8E          Aluno-2
 1010  RA-1271  FASE 8        NaN        NaN              8E       Aluno-1271
 1011  RA-1272  FASE 8        NaN        NaN              8E       Aluno-1272
 1012  RA-1273  FASE 8        NaN        NaN              8E       Aluno-1273
 1013  RA-1274  FASE 8        NaN        NaN              8E       Aluno-1274

              Data de Nasc                Idade     Gênero  Ano ingresso  ...  \
 0               6/17/2015                    8   Feminino          2023  ...
 1               5/31/2014                    9  Masculino          2023  ...
 2               2/25/2016                    7  Masculino          2023  ...
 3     2015-12-03 00:00:00  1900-01-08 00:00:00   Feminino          2023  ...
 4              11/13/2014                    8  Masculino          2023  ...
 ...                   ...                  ...        ...           ...  ...
 1009            5/17/2005                   18   Feminino          2017  ...
 1010           11/23/2004                   18   Feminino          2021  ...
 1011  2004-04-11 00:00:00  1900-01-18 00:00:00   Feminino          2021  ...
 1012           11/29/2005                   17   Feminino          2023  ...
 1013  2005-07-10 00:00:00  1900-01-18 00:00:00   Feminino          2021  ...

      Indicado Atingiu PV    IPV   IAN               Fase Ideal  Defasagem  \
 0         NaN        NaN  8.920  10.0       ALFA (1° e 2° ano)          0
 1         NaN        NaN  8.585   5.0     Fase 1 (3° e 4° ano)         -1
 2         NaN        NaN  6.260  10.0       ALFA (1° e 2° ano)          0
 3         NaN        NaN  8.500  10.0       ALFA (1° e 2° ano)          0
 4         NaN        NaN  7.915  10.0       ALFA (1° e 2° ano)          0
 ...       ...        ...    ...   ...                      ...        ...
 1009      NaN        NaN    NaN  10.0  Fase 8 (Universitários)          0
 1010      NaN        NaN    NaN  10.0  Fase 8 (Universitários)          0
 1011      NaN        NaN    NaN  10.0  Fase 8 (Universitários)          0
 1012      NaN        NaN    NaN  10.0           Fase 7 (3° EM)          1
 1013      NaN        NaN    NaN  10.0  Fase 8 (Universitários)          0

       Destaque IEG  Destaque IDA  Destaque IPV  Destaque IPV.1
 0              NaN           NaN           NaN             NaN
 1              NaN           NaN           NaN             NaN
 2              NaN           NaN           NaN             NaN
 3              NaN           NaN           NaN             NaN
 4              NaN           NaN           NaN             NaN
 ...            ...           ...           ...             ...
 1009           NaN           NaN           NaN             NaN
 1010           NaN           NaN           NaN             NaN
 1011           NaN           NaN           NaN             NaN
 1012           NaN           NaN           NaN             NaN
 1013           NaN           NaN           NaN             NaN

 [1014 rows x 48 columns],
 'PEDE2024':            RA  Fase INDE 2024 Pedra 2024           Turma Nome Anonimizado  \
 0     RA-1275  ALFA  7.611367   Ametista  ALFA A - G0/G1       Aluno-1275
 1     RA-1276  ALFA  8.002867    Topázio  ALFA A - G0/G1       Aluno-1276
 2     RA-1277  ALFA    7.9522   Ametista  ALFA A - G0/G1       Aluno-1277
 3      RA-868  ALFA  7.156367   Ametista  ALFA A - G0/G1        Aluno-868
 4     RA-1278  ALFA    5.4442    Quartzo  ALFA A - G0/G1       Aluno-1278
 ...       ...   ...       ...        ...             ...              ...
 1151  RA-1658     9   INCLUIR    INCLUIR               9       Aluno-1658
 1152  RA-1659     9   INCLUIR    INCLUIR               9       Aluno-1659
 1153  RA-1252     9   INCLUIR    INCLUIR               9       Aluno-1252
 1154  RA-1660     9   INCLUIR    INCLUIR               9       Aluno-1660
 1155  RA-1661     9   INCLUIR    INCLUIR               9       Aluno-1661

             Data de Nasc  Idade     Gênero  Ano ingresso  ...       IPV   IAN  \
 0    2016-07-28 00:00:00      8  Masculino          2024  ...  5.446667  10.0
 1    2016-10-16 00:00:00      8   Feminino          2024  ...  7.050000  10.0
 2    2016-08-16 00:00:00      8  Masculino          2024  ...  7.046667  10.0
 3    2015-11-08 00:00:00      8  Masculino          2023  ...  7.213333   5.0
 4    2015-03-22 00:00:00      9  Masculino          2024  ...  4.173333   5.0
 ...                  ...    ...        ...           ...  ...       ...   ...
 1151 2002-12-14 02:00:00     21  Masculino          2021  ...       NaN  10.0
 1152 2003-02-04 02:00:00     21  Masculino          2021  ...       NaN  10.0
 1153 2002-06-03 03:00:00     22   Feminino          2021  ...       NaN  10.0
 1154 2000-06-28 03:00:00     24   Feminino          2021  ...       NaN  10.0
 1155 2003-01-29 02:00:00     21   Feminino          2021  ...       NaN  10.0

                    Fase Ideal Defasagem Destaque IEG  Destaque IDA  \
 0          ALFA (1° e 2° ano)         0          NaN           NaN
 1          ALFA (1° e 2° ano)         0          NaN           NaN
 2          ALFA (1° e 2° ano)         0          NaN           NaN
 3        Fase 1 (3° e 4° ano)        -1          NaN           NaN
 4        Fase 1 (3° e 4° ano)        -1          NaN           NaN
 ...                       ...       ...          ...           ...
 1151  Fase 8 (Universitários)         1          NaN           NaN
 1152  Fase 8 (Universitários)         1          NaN           NaN
 1153  Fase 8 (Universitários)         1          NaN           NaN
 1154  Fase 8 (Universitários)         1          NaN           NaN
 1155  Fase 8 (Universitários)         1          NaN           NaN

       Destaque IPV                               Escola  Ativo/ Inativo  \
 0              NaN                EE Chácara Florida II        Cursando
 1              NaN                EE Chácara Florida II        Cursando
 2              NaN    EE Dom Pedro Villas Boas de Souza        Cursando
 3              NaN                EE Chácara Florida II        Cursando
 4              NaN            EM Etelvina Delfim Simões        Cursando
 ...            ...                                  ...             ...
 1151           NaN                     Faculdade (FIAP)        Cursando
 1152           NaN  Bolsista Universitário *Formado (a)        Cursando
 1153           NaN                     Faculdade (FIAP)        Cursando
 1154           NaN  Bolsista Universitário *Formado (a)        Cursando
 1155           NaN  Bolsista Universitário *Formado (a)        Cursando

       Ativo/ Inativo.1
 0             Cursando
 1             Cursando
 2             Cursando
 3             Cursando
 4             Cursando
 ...                ...
 1151          Cursando
 1152          Cursando
 1153          Cursando
 1154          Cursando
 1155          Cursando

 [1156 rows x 50 columns]}

In [4]:
df_2022 = df['PEDE2022']
df_2023 = df['PEDE2023']
df_2024 = df['PEDE2024']

In [5]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(10), int64(9), object(23)
memory usage: 282.3+ KB

In [6]:
df_2022[['Nº Av', 'Avaliador1', 'Rec Av1', 'Avaliador2', 'Rec Av2', 'Avaliador3', 'Rec Av3']].head()

,Nº Av,Avaliador1,Rec Av1,Avaliador2,Rec Av2,Avaliador3,Rec Av3
0,4,Avaliador-5,Mantido na Fase atual,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase
1,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase
2,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase + Bolsa
3,4,Avaliador-5,Promovido de Fase,Avaliador-27,Mantido na Fase atual,Avaliador-28,Mantido na Fase atual
4,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase + Bolsa

In [7]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(17)
memory usage: 380.4+ KB

In [8]:
df_2023.head()

,RA,Fase,INDE 2023,Pedra 2023,Turma,Nome Anonimizado,Data de Nasc,Idade,Gênero,Ano ingresso,...,Indicado,Atingiu PV,IPV,IAN,Fase Ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,Destaque IPV.1
0,RA-861,ALFA,9.31095,Topázio,ALFA A - G0/G1,Aluno-861,6/17/2015,8,Feminino,2023,...,NaN,NaN,8.920,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
1,RA-862,ALFA,8.22120,Topázio,ALFA A - G0/G1,Aluno-862,5/31/2014,9,Masculino,2023,...,NaN,NaN,8.585,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,NaN
2,RA-863,ALFA,5.92975,Quartzo,ALFA A - G0/G1,Aluno-863,2/25/2016,7,Masculino,2023,...,NaN,NaN,6.260,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
3,RA-864,ALFA,7.03400,Ametista,ALFA A - G0/G1,Aluno-864,2015-12-03 00:00:00,1900-01-08 00:00:00,Feminino,2023,...,NaN,NaN,8.500,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
4,RA-865,ALFA,8.15520,Topázio,ALFA A - G0/G1,Aluno-865,11/13/2014,8,Masculino,2023,...,NaN,NaN,7.915,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN

In [9]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   datetime64[ns]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               690 non-null    object
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: datetime64[ns](1), float64(23), int64(4), object(22)
memory usage: 451.7+ KB

## Identificar ano da pesquisa

In [10]:
df_2022['Ano Pesquisa'] = 2022
df_2023['Ano Pesquisa'] = 2023
df_2024['Ano Pesquisa'] = 2024

## Dropando colunas nulas

In [11]:
# Drop columns that are entirely null from df_2022
columns_to_drop_2022 = df_2022.columns[df_2022.isnull().all()].tolist()
if columns_to_drop_2022:
    df_2022 = df_2022.drop(columns=columns_to_drop_2022)
    print(f"Colunas totalmente nulas removidas de df_2022: {columns_to_drop_2022}")
else:
    print("Nenhuma coluna totalmente nula encontrada em df_2022.")

# Drop columns that are entirely null from df_2023
columns_to_drop_2023 = df_2023.columns[df_2023.isnull().all()].tolist()
if columns_to_drop_2023:
    df_2023 = df_2023.drop(columns=columns_to_drop_2023)
    print(f"Colunas totalmente nulas removidas de df_2023: {columns_to_drop_2023}")
else:
    print("Nenhuma coluna totalmente nula encontrada em df_2023.")

# Drop columns that are entirely null from df_2024
columns_to_drop_2024 = df_2024.columns[df_2024.isnull().all()].tolist()
if columns_to_drop_2024:
    df_2024 = df_2024.drop(columns=columns_to_drop_2024)
    print(f"Colunas totalmente nulas removidas de df_2024: {columns_to_drop_2024}")
else:
    print("Nenhuma coluna totalmente nula encontrada em df_2024.")

Nenhuma coluna totalmente nula encontrada em df_2022.
Colunas totalmente nulas removidas de df_2023: ['Pedra 23', 'INDE 23', 'Cg', 'Cf', 'Ct', 'Rec Av1', 'Rec Av2', 'Rec Av3', 'Rec Av4', 'Rec Psicologia', 'Indicado', 'Atingiu PV', 'Destaque IEG', 'Destaque IDA', 'Destaque IPV', 'Destaque IPV.1']
Colunas totalmente nulas removidas de df_2024: ['Cg', 'Cf', 'Ct', 'Rec Av1', 'Rec Av2', 'Rec Psicologia', 'Indicado', 'Atingiu PV', 'Destaque IEG', 'Destaque IDA', 'Destaque IPV']

## Padronizar o nome das colunas removendo os sufixos de ano

In [12]:
# Para df_2022: renomear 'INDE 22' para 'INDE'
df_2022 = df_2022.rename(columns={'INDE 22': 'INDE', 'Idade 22': 'Idade'})

# Para df_2023:
# Renomear 'INDE 2023' para 'INDE'
# Dropar 'INDE 22', 'INDE 23' e 'Pedra 23'
df_2023 = df_2023.rename(columns={'INDE 2023': 'INDE'})
df_2023 = df_2023.drop(columns=['INDE 22'], errors='ignore')

# Para df_2024:
# Renomear 'INDE 2024' para 'INDE'
# Dropar 'INDE 22' e 'INDE 23'
df_2024 = df_2024.rename(columns={'INDE 2024': 'INDE'})
df_2024 = df_2024.drop(columns=['INDE 22', 'INDE 23'], errors='ignore')

In [13]:
df_2023 = df_2023.rename(columns={'Pedra 2023': 'Pedra 23'})
df_2024 = df_2024.rename(columns={'Pedra 2024': 'Pedra 24'})

## Outras padronizações de nomes de colunas

In [14]:
# Para df_2022
df_2022 = df_2022.rename(columns={
    'Matem': 'Matematica',
    'Portug': 'Portugues',
    'Inglês': 'Ingles',
    'Defas': 'Defasagem',
    'Nome': 'Nome Anonimizado',
    'Fase ideal': 'Fase Ideal'
})

# Para df_2023
df_2023 = df_2023.rename(columns={
    'Mat': 'Matematica',
    'Por': 'Portugues',
    'Ing': 'Ingles'
})

# Para df_2024
df_2024 = df_2024.rename(columns={
    'Mat': 'Matematica',
    'Por': 'Portugues',
    'Ing': 'Ingles'
})

### Padronizar colunas de ano e data de nascimento

In [15]:
# Para df_2022: renomear 'Ano nasc' para 'Ano nascimento'
df_2022 = df_2022.rename(columns={'Ano nasc': 'Ano nascimento'})

In [16]:
# Para df_2023:
# Converter 'Data de Nasc' para datetime e extrair o ano
# df_2023['Data de Nasc'] has mixed formats, so we need to handle errors
df_2023['Data de Nasc'] = pd.to_datetime(df_2023['Data de Nasc'], errors='coerce', dayfirst=True)
df_2023['Ano nascimento'] = df_2023['Data de Nasc'].dt.year
# Dropar a coluna original 'Data de Nasc'
df_2023 = df_2023.drop(columns=['Data de Nasc'])

/tmp/ipykernel_3043/272933190.py:4: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_2023['Data de Nasc'] = pd.to_datetime(df_2023['Data de Nasc'], errors='coerce', dayfirst=True)

In [17]:
# Para df_2024:
# 'Data de Nasc' já é datetime, apenas extrair o ano
df_2024['Ano nascimento'] = df_2024['Data de Nasc'].dt.year
# Dropar a coluna original 'Data de Nasc'
df_2024 = df_2024.drop(columns=['Data de Nasc'])

### Verificar e dropar colunas duplicadas

In [28]:
# Verificar e dropar 'Destaque IPV.1' em df_2023
if 'Destaque IPV' in df_2023.columns and 'Destaque IPV.1' in df_2023.columns:
    if df_2023['Destaque IPV'].equals(df_2023['Destaque IPV.1']):
        print("Colunas 'Destaque IPV' e 'Destaque IPV.1' em df_2023 são idênticas. Removendo 'Destaque IPV.1'.")
        df_2023 = df_2023.drop(columns=['Destaque IPV.1'])
    else:
        print("Colunas 'Destaque IPV' e 'Destaque IPV.1' em df_2023 não são idênticas.")
else:
    print("Uma ou ambas as colunas 'Destaque IPV'/'Destaque IPV.1' não existem em df_2023.")

# Verificar e dropar 'Ativo/ Inativo.1' em df_2024
if 'Ativo/ Inativo' in df_2024.columns and 'Ativo/ Inativo.1' in df_2024.columns:
    if df_2024['Ativo/ Inativo'].equals(df_2024['Ativo/ Inativo.1']):
        print("Colunas 'Ativo/ Inativo' e 'Ativo/ Inativo.1' em df_2024 são idênticas. Removendo 'Ativo/ Inativo.1'.")
        df_2024 = df_2024.drop(columns=['Ativo/ Inativo.1'])
    else:
        print("Colunas 'Ativo/ Inativo' e 'Ativo/ Inativo.1' em df_2024 não são idênticas.")
else:
    print("Uma ou ambas as colunas 'Ativo/ Inativo'/'Ativo/ Inativo.1' não existem em df_2024.")

# Verificar e dropar 'Escola' em df_2024
if 'Escola' in df_2024.columns and 'Instituição de ensino' in df_2024.columns:
    if df_2024['Escola'].equals(df_2024['Instituição de ensino']):
        print("Colunas 'Escola' e 'Instituição de ensino' em df_2024 são idênticas. Removendo 'Escola'.")
        df_2024 = df_2024.drop(columns=['Escola'])
    else:
        print("Colunas 'Escola' e 'Instituição de ensino' em df_2024 não são idênticas.")
else:
    print("Uma ou ambas as colunas 'Escola' e 'Instituição de ensino' não existem em df_2024.")

Uma ou ambas as colunas 'Destaque IPV'/'Destaque IPV.1' não existem em df_2023.
Uma ou ambas as colunas 'Ativo/ Inativo'/'Ativo/ Inativo.1' não existem em df_2024.
Colunas 'Escola' e 'Instituição de ensino' em df_2024 não são idênticas.

In [32]:
df_2024[['Escola', 'Instituição de ensino']].head()

                              Escola Instituição de ensino
0              EE Chácara Florida II               Pública
1              EE Chácara Florida II               Pública
2  EE Dom Pedro Villas Boas de Souza               Pública
3              EE Chácara Florida II               Pública
4          EM Etelvina Delfim Simões               Pública

## Concatenar para o formato longo

In [19]:
df_long = pd.concat([df_2022, df_2023, df_2024], ignore_index=True)

In [20]:
df_long.head()

,RA,Fase,Turma,Nome Anonimizado,Ano nascimento,Idade,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,...,Destaque IDA,Destaque IPV,Ano Pesquisa,Pedra 23,IPP,Pedra 24,Avaliador5,Avaliador6,Escola,Ativo/ Inativo
0,RA-1,7,A,Aluno-1,2003,19,Menina,2016,Escola Pública,Ametista,...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RA-2,7,A,Aluno-2,2005,17,Menina,2017,Rede Decisão,Ametista,...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RA-3,7,A,Aluno-3,2005,17,Menina,2016,Rede Decisão,Ametista,...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Destaque: A sua boa integração aos Princípios ...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RA-4,7,A,Aluno-4,2005,17,Menino,2017,Rede Decisão,Ametista,...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RA-5,7,A,Aluno-5,2005,17,Menina,2016,Rede Decisão,Ametista,...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     3030 non-null   object
 1   Fase                   3030 non-null   object
 2   Turma                  3030 non-null   object
 3   Nome Anonimizado       3030 non-null   object
 4   Ano nascimento         3030 non-null   int64
 5   Idade                  3030 non-null   object
 6   Gênero                 3030 non-null   object
 7   Ano ingresso           3030 non-null   int64
 8   Instituição de ensino  3029 non-null   object
 9   Pedra 20               754 non-null    object
 10  Pedra 21               1061 non-null   object
 11  Pedra 22               1932 non-null   object
 12  INDE                   2883 non-null   object
 13  Cg                     860 non-null    float64
 14  Cf                     860 non-null    float64
 15  Ct                     860 non-null    float64
 16  Nº Av                  2954 non-null   float64
 17  Avaliador1             2827 non-null   object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             2827 non-null   object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             2034 non-null   object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             1051 non-null   object
 24  Rec Av4                296 non-null    object
 25  IAA                    2865 non-null   float64
 26  IEG                    2954 non-null   float64
 27  IPS                    2859 non-null   float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    2852 non-null   float64
 30  Matematica             2846 non-null   float64
 31  Portugues              2845 non-null   float64
 32  Ingles                 1091 non-null   float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    2852 non-null   float64
 36  IAN                    3030 non-null   float64
 37  Fase Ideal             3030 non-null   object
 38  Defasagem              3030 non-null   int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
 42  Ano Pesquisa           3030 non-null   int64
 43  Pedra 23               1621 non-null   object
 44  IPP                    1992 non-null   float64
 45  Pedra 24               1092 non-null   object
 46  Avaliador5             148 non-null    object
 47  Avaliador6             6 non-null      object
 48  Escola                 1155 non-null   object
 49  Ativo/ Inativo         1156 non-null   object
dtypes: float64(14), int64(4), object(32)
memory usage: 1.2+ MB

## Tirar as colunas de avaliação por falta de consistência dos dados

In [22]:
df_long = df_long.drop(columns=['Rec Av1', 'Rec Av2', 'Rec Av3', 'Rec Av4', 'Nº Av',
    'Avaliador1', 'Avaliador2', 'Avaliador3', 'Avaliador4', 'Avaliador5', 'Avaliador6'])

In [23]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     3030 non-null   object
 1   Fase                   3030 non-null   object
 2   Turma                  3030 non-null   object
 3   Nome Anonimizado       3030 non-null   object
 4   Ano nascimento         3030 non-null   int64
 5   Idade                  3030 non-null   object
 6   Gênero                 3030 non-null   object
 7   Ano ingresso           3030 non-null   int64
 8   Instituição de ensino  3029 non-null   object
 9   Pedra 20               754 non-null    object
 10  Pedra 21               1061 non-null   object
 11  Pedra 22               1932 non-null   object
 12  INDE                   2883 non-null   object
 13  Cg                     860 non-null    float64
 14  Cf                     860 non-null    float64
 15  Ct                     860 non-null    float64
 16  IAA                    2865 non-null   float64
 17  IEG                    2954 non-null   float64
 18  IPS                    2859 non-null   float64
 19  Rec Psicologia         860 non-null    object
 20  IDA                    2852 non-null   float64
 21  Matematica             2846 non-null   float64
 22  Portugues              2845 non-null   float64
 23  Ingles                 1091 non-null   float64
 24  Indicado               860 non-null    object
 25  Atingiu PV             860 non-null    object
 26  IPV                    2852 non-null   float64
 27  IAN                    3030 non-null   float64
 28  Fase Ideal             3030 non-null   object
 29  Defasagem              3030 non-null   int64
 30  Destaque IEG           860 non-null    object
 31  Destaque IDA           860 non-null    object
 32  Destaque IPV           860 non-null    object
 33  Ano Pesquisa           3030 non-null   int64
 34  Pedra 23               1621 non-null   object
 35  IPP                    1992 non-null   float64
 36  Pedra 24               1092 non-null   object
 37  Escola                 1155 non-null   object
 38  Ativo/ Inativo         1156 non-null   object
dtypes: float64(13), int64(4), object(22)
memory usage: 923.3+ KB

## Limpar espaços extras

In [24]:
# Limpa espaços extras para que 'Escola Pública' e ' Escola Pública ' sejam agrupados juntos na análise
cols_categoricas = ['Instituição de ensino', 'Pedra', 'Indicado', 'Atingiu PV']
for col in cols_categoricas:
    if col in df_long.columns:
        df_long[col] = df_long[col].astype(str).str.strip().str.title()
        # Volta valores NaN que viraram string 'Nan' pelo cast acima
        df_long[col] = df_long[col].replace('Nan', pd.NA)

## Reordenar Colunas do `df_long` para Análise

In [25]:
# Definir uma ordem lógica para as colunas
# Agrupar colunas semelhantes e colocar as mais importantes no início

# Colunas de identificação e tempo
ordered_columns = [
    'RA',
    'Nome Anonimizado',
    'Ano_Pesquisa',
    'Ano ingresso',
    'Ano nascimento',
    'Idade',
    'Gênero',
    'Fase',
    'Turma',
    'Fase Ideal',
    'Instituição de ensino',
    'Escola',
    'Ativo/ Inativo',

    # Colunas de Indicadores Globais
    'INDE',
    'Pedra 20', 'Pedra 21', 'Pedra 22', 'Pedra 23', 'Pedra 24',
    'Cg', 'Cf', 'Ct',

    # Indicadores de Desempenho e Engajamento
    'IAN',
    'Defasagem',
    'IAA',
    'IEG',
    'IPS',
    'IDA',
    'IPP',
    'IPV',

    # Notas
    'Matematica',
    'Portugues',
    'Ingles',

    # Recomendações e Destaques
    'Indicado',
    'Atingiu PV',
    'Destaque IEG',
    'Destaque IDA',
    'Destaque IPV',
    'Rec Psicologia'
]

# Filtrar as colunas que realmente existem em df_long
existing_columns = [col for col in ordered_columns if col in df_long.columns]

# Adicionar quaisquer colunas restantes que não foram especificadas na lista ordenada
remaining_columns = [col for col in df_long.columns if col not in existing_columns]

# Criar a ordem final das colunas
final_column_order = existing_columns + remaining_columns

# Reordenar o DataFrame
df_long = df_long[final_column_order]

print("Colunas de df_long reordenadas com sucesso.")
display(df_long.head())

Colunas de df_long reordenadas com sucesso.

,RA,Nome Anonimizado,Ano ingresso,Ano nascimento,Idade,Gênero,Fase,Turma,Fase Ideal,Instituição de ensino,...,Matematica,Portugues,Ingles,Indicado,Atingiu PV,Destaque IEG,Destaque IDA,Destaque IPV,Rec Psicologia,Ano Pesquisa
0,RA-1,Aluno-1,2016,2003,19,Menina,7,A,Fase 8 (Universitários),Escola Pública,...,2.7,3.5,6.0,Sim,Não,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,Requer avaliação,2022
1,RA-2,Aluno-2,2017,2005,17,Menina,7,A,Fase 7 (3º EM),Rede Decisão,...,6.3,4.5,9.7,Não,Não,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,Sem limitações,2022
2,RA-3,Aluno-3,2016,2005,17,Menina,7,A,Fase 7 (3º EM),Rede Decisão,...,5.8,4.0,6.9,Não,Não,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Destaque: A sua boa integração aos Princípios ...,Sem limitações,2022
3,RA-4,Aluno-4,2017,2005,17,Menino,7,A,Fase 7 (3º EM),Rede Decisão,...,2.8,3.5,8.7,Não,Não,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,Requer avaliação,2022
4,RA-5,Aluno-5,2016,2005,17,Menina,7,A,Fase 7 (3º EM),Rede Decisão,...,7.0,2.9,5.7,Não,Não,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...,Requer avaliação,2022

In [26]:
# c) Ordenar o dataframe para facilitar a visualização da jornada por aluno no tempo
df_long.sort_values(by=['RA', 'Ano Pesquisa'], inplace=True)
df_long.reset_index(drop=True, inplace=True)

In [27]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     3030 non-null   object
 1   Nome Anonimizado       3030 non-null   object
 2   Ano ingresso           3030 non-null   int64
 3   Ano nascimento         3030 non-null   int64
 4   Idade                  3030 non-null   object
 5   Gênero                 3030 non-null   object
 6   Fase                   3030 non-null   object
 7   Turma                  3030 non-null   object
 8   Fase Ideal             3030 non-null   object
 9   Instituição de ensino  3029 non-null   object
 10  Escola                 1155 non-null   object
 11  Ativo/ Inativo         1156 non-null   object
 12  INDE                   2883 non-null   object
 13  Pedra 20               754 non-null    object
 14  Pedra 21               1061 non-null   object
 15  Pedra 22               1932 non-null   object
 16  Pedra 23               1621 non-null   object
 17  Pedra 24               1092 non-null   object
 18  Cg                     860 non-null    float64
 19  Cf                     860 non-null    float64
 20  Ct                     860 non-null    float64
 21  IAN                    3030 non-null   float64
 22  Defasagem              3030 non-null   int64
 23  IAA                    2865 non-null   float64
 24  IEG                    2954 non-null   float64
 25  IPS                    2859 non-null   float64
 26  IDA                    2852 non-null   float64
 27  IPP                    1992 non-null   float64
 28  IPV                    2852 non-null   float64
 29  Matematica             2846 non-null   float64
 30  Portugues              2845 non-null   float64
 31  Ingles                 1091 non-null   float64
 32  Indicado               860 non-null    object
 33  Atingiu PV             860 non-null    object
 34  Destaque IEG           860 non-null    object
 35  Destaque IDA           860 non-null    object
 36  Destaque IPV           860 non-null    object
 37  Rec Psicologia         860 non-null    object
 38  Ano Pesquisa           3030 non-null   int64
dtypes: float64(13), int64(4), object(22)
memory usage: 923.3+ KB